# Create map service: OSM local tile server, create database server, geoserver
version: "3"

services: 
  mapdb:
    build:
      context: ./OSMDB/
      dockerfile: osmdb.dockerfile
    restart: always
    container_name: osmdb
    environment: 
      POSTGRES_DB: "osmdb"
      POSTGRES_USER: "osmrender"
      POSTGRES_PASSWORD: "osmpassword"
      POSTGRES_PORT_LH: 50101
      POSTGRES_DATA_VOLUME: "/hdd2/db_data/osmdb_data"
    volumes: 
      - "/hdd2/db_data/osmdb_data:/var/lib/postgresql/data"
    ports:
      - 50101:5432
  mapdbadmin:
    image: dpage/pgadmin4
    restart: always
    links:
      - mapdb
    container_name: mapdbadmin
    environment:
       PGADMIN_DEFAULT_EMAIL: "admin@sml"
       PGADMIN_DEFAULT_PASSWORD: "pgadminpassword"
    volumes:
      - "/ssd/data0/pgadmin4_data:/var/lib/pgadmin"
    ports:
      - 50102:80
    depends_on: 
      - mapdb
      - osmts
  osmts:
    build:
      context: ./OSMTS/
      dockerfile: osmts.dockerfile
    links:
      - mapdb
    restart: always
    container_name: osmts
    environment: 
      OSM_IMPORTDIR: "osm_files"
      CONFIGDIR: "config"
      STYLE_DEV: "config/Stylesheet/style_dev"
      IMPORT_RAM_CACHE: 32000
      IMPORT_PROCESS_NUM: 12
      POSTGRES_DB: "osmdb"
      POSTGRES_USER: "osmrender"
      POSTGRES_PASSWORD: "osmpassword"

    volumes: 
      - "/ssd/data0/osm_data:/data:z"
    depends_on: 
      - mapdb
    ports:
      - 50100:80
#  kosmtik:
#    build:
#      context: kosmtik
#      dockerfile: kosmtik.dockerfile
#    links:
#      - mapdb
#    restart: always
#    container_name: kosmtik
#    environment: 
#      PROJECTDIR: "config/Stylesheet/style_dev"
#      PGHOST: "mapdb"
#      PGDATABASE: "osmdb"
#      PGUSER: "osmrender"
#      PGPASSWORD: "osmpassword"
#    volumes: 
#      - "/ssd/data0/osm_data:/data:z"
#    depends_on: 
#      - mapdb
#      - osmts
#    ports: 
#      - 50103:6789
#      - 50104:8111


